// Original synthetic transport data. These are not product templates or rates.
export const OPERATIONAL_CASE_IDS = [
  'T03',
  'T04',
  'T05',
  'T06',
  'T07',
  'T08',
  'T09',
  'T10',
  'T11',
  'T12',
] as const;
export type OperationalCaseId = (typeof OPERATIONAL_CASE_IDS)[number];
export function syntheticRequirements() {
  return {
    version: 1,
    projectName: 'Fictional Cedar Workshop',
    projectType: 'synthetic-control',
    summary: 'Original synthetic requirements.',
    sourceDocuments: {},
    validations: [],
    conflicts: [],
    automationTriggers: {
      orderReminders: false,
      rainDelayCalculations: false,
      noticeCountdowns: false,
    },
    legalAdministration: {},
    commercialsAndClaims: {},
    subStructureAndGround: {},
    inclusionsAndExclusions: {},
    utilityInfrastructure: {},
    wetAreaCompliance: {},
    safetyAndSiteLogistics: {},
  };
}
export function syntheticOfferWorkspace() {
  return {
    schemaVersion: 6,
    calcVersion: 2,
    adminContentVersion: 0,
    job: {
      reference: 'SYNTHETIC-101',
      revision: '1',
      clientNames: 'Amelia Fiction',
      clientEmail: 'amelia@client.example',
      clientPhone: 'fictional-phone',
      currentLocation: 'Fictional owner address',
      siteAddress: 'Fictional Cedar site',
      buildType: 'synthetic',
      groundFloorSqm: 80,
      firstFloorSqm: 0,
      garageSqm: 0,
      alfrescoPorchSqm: 0,
      porchSqm: 0,
      grannyFlatSqm: 0,
      validUntil: '2026-11-01',
      preparedBy: 'Synthetic control',
      owners: [
        {
          id: 'synthetic-owner',
          kind: 'individual',
          displayName: 'Amelia Fiction',
          currentLocation: 'Fictional owner address',
          abn: '',
          signatories: [
            {
              id: 'synthetic-signer',
              name: 'Amelia Fiction',
              email: 'amelia@client.example',
              phone: '',
              mobile: '',
              capacity: 'Owner',
            },
          ],
        },
      ],
    },
    costLines: [
      {
        id: 'synthetic-line',
        stageCode: 'slab',
        itemName: 'Synthetic construction',
        buildingSequenceTasks: [],
        offerTenderLineItem: 'Synthetic construction',
        tradeOrVendor: '',
        notesOrSpec: '',
        costExGstCents: 10000000,
        includedInContract: true,
      },
    ],
    allowances: [],
    exclusions: [],
    draft: {
      headline: 'Synthetic offer',
      introText: 'Original synthetic copy.',
      exclusionBullets: [],
      inclusionHighlights: [],
      inclusionSchedule: [],
      termsSummary: 'Synthetic terms.',
    },
    areaCalculator: {
      slabCost: 0,
      dropEdgeBeamSurfaceArea: 0,
      numberOfTrucks: 0,
      steel: 0,
      installer: 0,
      eaves: 0,
      bricksGroundFloor: 0,
      bricksFirstFloor: 0,
      bricksPillar: 0,
      tieCost: 0,
    },
    pricingSettings: {
      royalConstructionOverheadPct: 0,
      royalConstructionFeePct: 0,
      gstRate: 0.1,
      hbcfTotalContractValue: 0,
      hbcfRate: 0,
      homeWarrantyHbcfFixed: 0,
      impactFeeFixed: 0,
      loadingChargePercentage: 0,
    },
    paymentSchedule: [],
    rateCardProduct: 'DOUBLE_STOREY',
    rateCardTier: 'MID',
    overrideReason: '',
    priceAdjustmentLabel: '',
    selectedPriceCents: 11000000,
    standardPriceCents: 11000000,
    images: {},
    tenderGate: {
      needsArchitecturalPlan: null,
      architecturalPlanFeeCollected: false,
      architecturalPlanUploaded: null,
      architecturalPlanDesignChanges: null,
    },
  };
}
